version: "3.9"

services:
  client:
    container_name: client-container
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - 3000:3000

  server:
    container_name: server-container
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 4000:4000
